### ISSUE TITLE
OAUTH2_PROXY_ALLOWED_ROLE is not effective

### ISSUE THREAD

**Issue by petrkalina** [dcm4che-dockerfiles/oauth2-proxy#1]
docs:

- oauth
```
j4care@demo:/opt/j4care/docker-stack$ docker exec -it ca03e76f667f /bin/oauth2-proxy --help | grep "allowed-role"
      --allowed-role strings                       (keycloak-oidc) restrict logins to members of these roles (may be given multiple times)
```
- image: https://github.com/dcm4che-dockerfiles/oauth2-proxy/blob/master/README.md
```
Alternatively above options may also be specified by corresponding environment variables OAUTH2_PROXY_{option-name-in captial-letters-and-underscores}
```

config:

- default LDAP/oauth install with env
```
OAUTH2_PROXY_ALLOWED_ROLE=auditlog
OAUTH2_PROXY_CLIENT_ID=kibana
OAUTH2_PROXY_CLIENT_SECRET=<secure-value>
OAUTH2_PROXY_HTTPS_ADDRESS=0.0.0.0:8643
OAUTH2_PROXY_OIDC_ISSUER_URL=https://demo.j4care.com:8843/realms/dcm4che
OAUTH2_PROXY_PROVIDER=keycloak-oidc
OAUTH2_PROXY_REDIRECT_URL=https://demo.j4care.com:8643/oauth2/callback
OAUTH2_PROXY_UPSTREAMS=http://kibana:5601
```
- in keycloak kibana client as per default install with
```
KIBANA_CLIENT_SECRET=<secure value>
KIBANA_REDIRECT_URL=https://demo.j4care.com:8643/*
```

test:

- in KC console create user `test-auditlog-role` and set credentials, but do not assign `auditlog` role
- logout, access the `https://..:8643` address
- in login dialog, log in as `test-auditlog-role` user
- kibana is displayed, even if the user does not have OAUTH2_PROXY_ALLOWED_ROLE assigned

**Comment by vrindanayak** [comment]
Fixed by changing 
````
OAUTH2_PROXY_ALLOWED_ROLE: auditlog
````
to
````
OAUTH2_PROXY_ALLOWED_ROLES: auditlog
````

and tested with open source version of [Run secured archive services and Elastic Stack on a single host](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-secured-archive-services-and-Elastic-Stack-on-a-single-host) setup on local system.
- [secure-arc-elk-oauth.zip](https://github.com/dcm4che-dockerfiles/oauth2-proxy/files/9488861/secure-arc-elk-oauth.zip)

Verification with open source default users `root` having `auditlog` role, whereas `admin` and `user` users not having this role mapped to them by default.
- [issue1.pdf](https://github.com/dcm4che-dockerfiles/oauth2-proxy/files/9488936/issue1.pdf)


Fixed related references
- [secure - docker-compose-logstash.yml](https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/commit/5415584a2e2f40850c8727aef78c913f936489b2)
- [secure-ui - docker-compose-logstash.yml](https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/commit/11b73607ff99fb7dba99b527930f785c9d058e72)
- [Wiki - docker-compose.yml](https://raw.githubusercontent.com/wiki/dcm4che/dcm4chee-arc-light/docker/docker-compose.yml)
- [Secure Kibana using OAuth2 Proxy](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Secure-Kibana-using-OAuth2-Proxy/_compare/0bca445a8a83005bef1a8fe0fc3d25db3d734727)
- [Run secured archive services and Elastic Stack on a single host](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-secured-archive-services-and-Elastic-Stack-on-a-single-host/_compare/8ca31e152cf9b4055d1e77229dcc809ae49707e6...0bca445a8a83005bef1a8fe0fc3d25db3d734727)
- [Distribute secured archive services and Elastic Stack over several hosts without Docker Swarm](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Distribute-secured-archive-services-and-Elastic-Stack-over-several-hosts-without-Docker-Swarm/_compare/8ca31e152cf9b4055d1e77229dcc809ae49707e6...0bca445a8a83005bef1a8fe0fc3d25db3d734727)
- [Distribute secured archive services and Elastic Stack over several hosts using Docker Swarm](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Distribute-secured-archive-services-and-Elastic-Stack-over-several-hosts-using-Docker-Swarm/_compare/17df03f9890b3350878ac3ce160b7da088cba5a9...0bca445a8a83005bef1a8fe0fc3d25db3d734727)
